# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Maven core artifacts are provided by the running Maven, so do not update
      # to prevent consuming something unavailable.
      - dependency-name: "org.apache.maven:*"
      # Per https://codehaus-plexus.github.io/plexus-utils/ pin plexus-xml to 3
      # for Maven 3 compatibility, as plexus-xml 4 works only in Maven 4.
      - dependency-name: "org.codehaus.plexus:plexus-xml"
        versions: [">=4.0.0"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
