# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Maven core artifacts are provided by the running Maven, so do not update
      # to prevent consuming something unavailable.
      - dependency-name: "org.apache.maven:*"
      # https://lists.apache.org/thread/ltd1g1dbv0lqqdw5q941gmrkfyn6m87m
      - dependency-name: "org.apache.maven.shared:maven-filtering"
        versions: [">=3.3.2"]
      - dependency-name: "org.codehaus.plexus:plexus-utils"
        versions: [">=4.0.0"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
