/* This file is used by the Jenkins' project continuous integration infrastructure
 * to build the plugin and verify there are no issues with pull requests 
 *
 * `buildPlugin` step provided by: https://github.com/jenkins-infra/pipeline-library 
 */

buildPlugin()
